micronaut:
  application:
    name: checkout
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  swagger:
    enabled: true
    paths: META-INF/swagger
    expand:
      operations: true
